#!/bin/sh
echo "RABBITMQ_HOST: $RABBITMQ_HOST"
echo "RABBITMQ_PORT: $RABBITMQ_PORT"
echo "RABBITMQ_USERNAME: $RABBITMQ_USERNAME"
echo "RABBITMQ_PASSWORD: $RABBITMQ_PASSWORD"
echo "GRAPHITE_HOST: $GRAPHITE_HOST"
echo "GRAPHITE_PORT: $GRAPHITE_PORT"

exec /app/rabbitmq-graphite-tool -graphite="$GRAPHITE_HOST:$GRAPHITE_PORT" -rabbitmq-mgmt-uri="http://$RABBITMQ_USERNAME:$RABBITMQ_PASSWORD@$RABBITMQ_HOST:$RABBITMQ_MGMT_PORT" -rabbitmq-uri="amqp://$RABBITMQ_USERNAME:$RABBITMQ_PASSWORD@$RABBITMQ_HOST:$RABBITMQ_PORT"